CREATE DATABASE RAW;
CREATE SCHEMA RAW.SOURCE;
CREATE DATABASE DEV_SANDBOX;
CREATE SCHEMA DEV_SANDBOX.VD;

CREATE SCHEMA SOURCE;
CREATE SCHEMA RAW.VD;

CREATE OR REPLACE USER CLI_USER
PASSWORD = ''
  LOGIN_NAME = CLI_USER
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_ROLE = ACCOUNTADMIN
  DEFAULT_WAREHOUSE = COMPUTE_WH;

GRANT ROLE ACCOUNTADMIN TO USER CLI_USER;

ALTER USER CLI_USER
SET RSA_PUBLIC_KEY='';
